name: Déploiement sur Serveur Personnel

on:
  push:
    branches:
      - main  # Déclenchement lors de push sur la branche principale
  workflow_dispatch:  # Permet le déclenchement manuel du workflow

jobs:
  deploy:
    runs-on: [self-hosted]
    steps:
      - name: Cloner le dépôt
        uses: actions/checkout@v2

      - name: Setup Python environment on Windows
        if: ${{ runner.os == 'Windows' }}
        run: |
          python -m venv venv
          .\venv\Scripts\Activate
          
      - name: Setup Python environment on Unix
        if: ${{ runner.os != 'Windows' }}
        run: |
          python -m venv venv
          source venv/bin/activate
          
      - name: Installer les dépendances
        run: |
          venv\Scripts\pip install -r requirements.txt
          
      - name: Configurer l'authtoken ngrok
        run: |
          ngrok config add-authtoken 2NQ1kLappbIbXUFI4mTuakB1vyM_7dZnj3yQDVSU7Hiru2RRw
          
      - name: Démarrer l'application FastAPI avec ngrok
        run: |
          if [[ "$RUNNER_OS" == "Windows" ]]; then
            Start-Process "start_app.sh"
          else
            chmod +x start_app.sh
            ./start_app.sh &
          fi

      - name: Récupérer le lien ngrok
        run: |
          # Attendre que ngrok démarre et configure le tunnel
          sleep 5
          # Utiliser l'API locale pour récupérer l'URL
          curl -s http://localhost:4040/api/tunnels | jq -r '.tunnels[0].public_url' > ngrok_url.txt
          
      - name: Afficher le lien ngrok
        run: |
          cat ngrok_url.txt
