name: Déploiement sur Serveur Personnel

on:
  push:
    branches:
      - main  # Déclenchement lors de push sur la branche principale
  workflow_dispatch:  # Permet le déclenchement manuel du workflow

jobs:
  deploy:
    runs-on: [self-hosted]
    steps:
      - name: Cloner le dépôt
        uses: actions/checkout@v2

      - name: Setup Python environment on Windows
        if: ${{ runner.os == 'Windows' }}
        run: |
          python -m venv venv
          .\venv\Scripts\Activate

      - name: Setup Python environment on Unix
        if: ${{ runner.os != 'Windows' }}
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Installer les dépendances
        run: |
          venv\Scripts\pip install -r requirements.txt

      - name: Configurer l'authtoken ngrok
        run: |
          ngrok config add-authtoken 2NQ1kLappbIbXUFI4mTuakB1vyM_7dZnj3yQDVSU7Hiru2RRw

      - name: Démarrer l'application FastAPI avec ngrok
        run: |
          chmod +x start_app.sh
          ./start_app.sh

      - name: Afficher l'URL ngrok
        shell: bash
        run: |
          sleep 5  # Attend que ngrok démarre
          ngrok_url=$(grep -o 'https://[a-z0-9]*\.ngrok\.io' ngrok.log | head -1)
          echo "URL publique de ngrok: $ngrok_url"



