name: Déploiement sur Serveur Personnel

on:
  push:
    branches:
      - main  # Déclenchement lors de push sur la branche principale
  workflow_dispatch:  # Permet le déclenchement manuel du workflow

jobs:
  deploy:
    runs-on: [self-hosted]
    steps:
      - name: Cloner le dépôt
        uses: actions/checkout@v2

      - name: Setup Python environment on Windows
        if: ${{ runner.os == 'Windows' }}
        run: |
          python -m venv venv
          .\venv\Scripts\Activate
          
      - name: Setup Python environment on Unix
        if: ${{ runner.os != 'Windows' }}
        run: |
          python -m venv venv
          source venv/bin/activate
          
      - name: Installer les dépendances
        run: |
          venv\Scripts\pip install -r requirements.txt

      - name: Démarrer l'application FastAPI avec ngrok
        shell: bash
        run: |
          chmod +x start_app.sh
          ./start_app.sh &
      
      - name: Attendre ngrok et récupérer l'URL
        run: |
          sleep 10  # Attendre que ngrok démarre
          NGROK_URL=$(curl -s http://localhost:4040/api/tunnels | jq -r '.tunnels[0].public_url')
          echo "L'URL publique ngrok est : $NGROK_URL" > ngrok_url.txt
      
      - name: Afficher l'URL ngrok
        run: |
          cat ngrok_url.txt
