name: Déploiement sur Serveur Personnel

on:
  push:
    branches:
      - main  # Déclenchement lors de push sur la branche principale
  workflow_dispatch:  # Permet le déclenchement manuel du workflow

jobs:
  deploy:
    runs-on: [self-hosted]
    steps:
      - name: Cloner le dépôt
        uses: actions/checkout@v2

      - name: Setup Python environment on Windows
        if: ${{ runner.os == 'Windows' }}
        run: |
          python -m venv venv
          .\venv\Scripts\Activate
          
      - name: Setup Python environment on Unix
        if: ${{ runner.os != 'Windows' }}
        run: |
          python -m venv venv
          source venv/bin/activate
          
      - name: Installer les dépendances
        run: |
          venv\Scripts\pip install -r requirements.txt

      # Supprimer la configuration authtoken puisque déjà spécifiée dans ngrok.yml
          
      - name: Démarrer l'application FastAPI avec ngrok
        run: |
          chmod +x scripts/start_app.sh
          ./scripts/start_app.sh
