name: Déployer FastAPI sur le serveur local

on:
  push:
    branches:
      - main  # Déclenche le workflow lors d'un push sur la branche principale

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Cloner le dépôt
        uses: actions/checkout@v2
      
      - name: Configurer SSH
        env:
          SSH_KEY: ${{ secrets.SSH_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H "VOTRE_IP" >> ~/.ssh/known_hosts
      
      - name: Déployer sur le serveur
        run: |
          ssh -o StrictHostKeyChecking=no louis@10.146.6.137 "pkill -f uvicorn || true"
          ssh -o StrictHostKeyChecking=no louis@10.146.6.137 "cd E:\AXELIA && nohup uvicorn app:app --host 0.0.0.0 --port 8000 &"
